
/// Input and stateful data for widget interaction.
#[derive(Debug, Default)]
pub struct UiState {
    /// Currently active widget id (pressed/dragging).
    active: Option<WidgetId>,
    /// Widget id currently under pointer hover.
    hot: Option<WidgetId>,
    /// Pointer position at the start of a drag gesture.
    drag_start: Option<Point>,
    /// Value captured when dragging begins.
    drag_value: f32,
    /// Dropdown currently opened this frame, if any.
    open_dropdown: Option<WidgetId>,
    /// Cached layout measurements keyed by container id.
    layout: LayoutState,
    /// Deferred dropdown overlays to render after widgets.
    overlays: Vec<DropdownOverlay>,
    /// Tracks whether this frame already consumed mouse-press input.
    consume_mouse_pressed: bool,
    /// Most recently measured root frame size.
    root_frame_size: Option<Size>,
    /// Whether root frame sizing was updated this frame.
    root_frame_used: bool,
    /// Latest dropdown popup request generated while rendering controls.
    #[cfg_attr(not(target_os = "windows"), allow(dead_code))]
    dropdown_popup_request: Option<DropdownPopupRequest>,
    /// Pending popup outcome generated by host-level native popup handling.
    #[cfg_attr(not(target_os = "windows"), allow(dead_code))]
    dropdown_popup_result: Option<DropdownPopupResult>,
    /// Design-to-surface transform used for host popup anchoring.
    #[cfg_attr(not(target_os = "windows"), allow(dead_code))]
    surface_transform: UiSurfaceTransform,
}

/// Cached container sizes for auto layout.
#[derive(Debug, Default)]
struct LayoutState {
    /// Last measured size for each keyed layout container.
    sizes: HashMap<WidgetId, Size>,
}

impl LayoutState {
    /// Return the cached size for a container id.
    fn get(&self, id: WidgetId) -> Option<Size> {
        self.sizes.get(&id).copied()
    }

    /// Update the cached size for a container id.
    fn set(&mut self, id: WidgetId, size: Size) {
        self.sizes.insert(id, size);
    }
}

impl UiState {
    #[cfg_attr(not(target_os = "windows"), allow(dead_code))]
    /// Start a new frame and reset one-frame root-size tracking.
    pub(crate) fn begin_frame(&mut self) {
        self.root_frame_used = false;
        self.root_frame_size = None;
        self.dropdown_popup_request = None;
    }

    /// Store the latest measured root frame size for host integrations.
    pub(crate) fn set_root_frame_size(&mut self, size: Size) {
        self.root_frame_used = true;
        self.root_frame_size = Some(size);
    }

    #[cfg_attr(not(target_os = "windows"), allow(dead_code))]
    /// Take and clear the most recent root frame size.
    pub(crate) fn take_root_frame_size(&mut self) -> Option<Size> {
        self.root_frame_size.take()
    }

    /// Update the design-to-surface transform for this frame.
    #[cfg_attr(not(target_os = "windows"), allow(dead_code))]
    pub(crate) fn set_surface_transform(
        &mut self,
        scale_x: f32,
        scale_y: f32,
        offset_x: f32,
        offset_y: f32,
    ) {
        self.surface_transform = UiSurfaceTransform {
            scale_x,
            scale_y,
            offset_x,
            offset_y,
        };
    }

    /// Convert a design-space rectangle into surface-space coordinates.
    #[cfg_attr(not(target_os = "windows"), allow(dead_code))]
    pub(crate) fn design_rect_to_surface(&self, rect: Rect) -> Rect {
        fn map_axis(value: i32, scale: f32, offset: f32) -> i32 {
            ((value as f32) * scale + offset).round() as i32
        }

        fn map_extent(value: u32, scale: f32) -> u32 {
            ((value as f32) * scale).round().max(1.0) as u32
        }

        Rect {
            origin: Point {
                x: map_axis(
                    rect.origin.x,
                    self.surface_transform.scale_x,
                    self.surface_transform.offset_x,
                ),
                y: map_axis(
                    rect.origin.y,
                    self.surface_transform.scale_y,
                    self.surface_transform.offset_y,
                ),
            },
            size: Size {
                width: map_extent(rect.size.width, self.surface_transform.scale_x),
                height: map_extent(rect.size.height, self.surface_transform.scale_y),
            },
        }
    }

    /// Queue a native dropdown popup request for host-level handling.
    #[cfg_attr(not(target_os = "windows"), allow(dead_code))]
    pub(crate) fn queue_dropdown_popup_request(&mut self, request: DropdownPopupRequest) {
        self.dropdown_popup_request = Some(request);
    }

    /// Take the latest queued dropdown popup request.
    #[cfg_attr(not(target_os = "windows"), allow(dead_code))]
    pub(crate) fn take_dropdown_popup_request(&mut self) -> Option<DropdownPopupRequest> {
        self.dropdown_popup_request.take()
    }

    /// Store a popup outcome from host-level native menu interaction.
    #[cfg_attr(not(target_os = "windows"), allow(dead_code))]
    pub(crate) fn set_dropdown_popup_result(&mut self, result: DropdownPopupResult) {
        self.dropdown_popup_result = Some(result);
    }

    /// Take a popup outcome for the given dropdown id.
    #[cfg_attr(not(target_os = "windows"), allow(dead_code))]
    pub(crate) fn take_dropdown_popup_result_for(
        &mut self,
        dropdown_id: WidgetId,
    ) -> Option<DropdownPopupResult> {
        match self.dropdown_popup_result {
            Some(DropdownPopupResult::Selected { dropdown_id: id, .. })
            | Some(DropdownPopupResult::Closed { dropdown_id: id })
                if id == dropdown_id =>
            {
                self.dropdown_popup_result.take()
            }
            _ => None,
        }
    }

    /// Clear the currently open dropdown state.
    #[cfg_attr(not(target_os = "windows"), allow(dead_code))]
    pub(crate) fn clear_open_dropdown(&mut self) {
        self.open_dropdown = None;
    }
}

/// Frame transform used to map design-space rectangles into surface-space.
#[derive(Clone, Copy, Debug)]
struct UiSurfaceTransform {
    /// Horizontal scale from design space to surface space.
    scale_x: f32,
    /// Vertical scale from design space to surface space.
    scale_y: f32,
    /// Horizontal surface offset in pixels.
    offset_x: f32,
    /// Vertical surface offset in pixels.
    offset_y: f32,
}

impl Default for UiSurfaceTransform {
    fn default() -> Self {
        Self {
            scale_x: 1.0,
            scale_y: 1.0,
            offset_x: 0.0,
            offset_y: 0.0,
        }
    }
}

/// Native-popup request payload for dropdown menus.
#[cfg_attr(not(target_os = "windows"), allow(dead_code))]
#[derive(Clone, Debug)]
pub(crate) struct DropdownPopupRequest {
    /// Stable dropdown widget id.
    pub(crate) dropdown_id: WidgetId,
    /// Dropdown control rectangle in surface/client coordinates.
    pub(crate) control_rect_surface: Rect,
    /// Option labels to render/select.
    pub(crate) options: Vec<String>,
    /// Currently selected option index.
    pub(crate) selected: usize,
    /// Preferred direction derived from local layout constraints.
    pub(crate) open_up: bool,
}

/// Native-popup outcome fed back into dropdown widgets.
#[cfg_attr(not(target_os = "windows"), allow(dead_code))]
#[derive(Clone, Copy, Debug)]
pub(crate) enum DropdownPopupResult {
    /// A specific option was selected.
    Selected {
        /// Dropdown widget identifier associated with this selection.
        dropdown_id: WidgetId,
        /// Selected option index.
        index: usize,
    },
    /// Popup closed without changing selection.
    Closed {
        /// Dropdown widget identifier associated with this closure.
        dropdown_id: WidgetId,
    },
}

/// Deferred dropdown overlay drawing data.
#[derive(Clone, Debug)]
struct DropdownOverlay {
    /// Rectangle of the closed dropdown control.
    base_rect: Rect,
    /// Option labels rendered in the overlay menu.
    options: Vec<String>,
    /// Option index currently hovered by the pointer.
    hovered: Option<usize>,
    /// Whether overlay options render upward instead of downward.
    open_up: bool,
    /// Clip rectangle used for popup visibility (typically full canvas bounds).
    clip_rect: Rect,
}
